# Site settings
title: Diamond
description: Welcome To My Blog
url: “atukenov.github.io”
author:
  name: “Almaz Tukenov”
  email: “almaz.t97@gmail.com“
  url: 

# Build settings
baseurl: /atukenov.github.io/
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.1.0"

# Gems
gems: [jekyll-paginate]

# Options
custom_header: false
custom_nav_footer: false
reverse: true
